---
- hosts: localhost
  gather_facts: false

  vars_files:
    - "vars/variables.yml"

  roles:
    - role: environment
      tags: [environment]
    - role: dev_environment
      tags: [dev]
    - role: dotfiles
      tags: [dotfiles]
