---
- name: Update the brew repositories and install system programs
  block:
    - name: "Install formulae programs"
      community.general.homebrew:
        name: "{{ programs.formulae }}"
        update_homebrew: true
    - name: "Install casks programs"
      community.general.homebrew_cask:
        name: "{{ programs.casks }}"
    - name: "Run OSX configuration"
      ansible.builtin.import_tasks: osx_user.yml
