---
- name: Install web browser.
  pacman:
    name: vivaldi
    state: present
- name: Install email client.
  pacman:
    name: thunderbird
    state: present
- name: Install GIMP.
  pacman:
    name: gimp
    state: present
