---
- name: Update the repositories.
  become: true
  pacman: update_cache=yes

- name: Install system packages.
  become: true
  pacman:
    name: "{{ packages }}"
    state: present

- name: Update xdg-user-dirs.
  command:
    cmd: xdg-user-dirs-update
    creates: "{{home_dir}}/Pictures"
